### ISSUE TITLE
To-Do-List Peer Review

### ISSUE THREAD

**Issue by frempongdev** [Habtamu210/To-do-list#3]
### Hi Habtamu ✋🏿,
 Great work on your project so far. You did well by completing all project requirements, however, there are a few changes ♻️ I would recommend you make.
 
  - [ ] Kindly make sure that your README.md file accurately describes the project. An accurate README file gives an overview of the project, explains the motivation behind it, lists the technologies used, provides instructions on how to install and run the project, and includes a link to a live demo (if available) 
  
I recommend you check [this link](https://coding-boot-camp.github.io/full-stack/github/professional-readme-guide) as a guide on writing a professional README.
  - [ ] Please deploy your page and add a link to the readme file as a live demo. Deploying the page and adding a link to the live demo is important because it allows others to see the project in action and interact with it. Here is [a link](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site) to help you easily deploy your page. 
  
Kindly remember to add your deployment link to your README.mf file. 
  - [ ] Kindly note that Linters are to be enabled as a requirement for Microverse Projects. Linters can also help to improve the quality of code and make it easier identify and fix errors in code.
  
Please Check [Line 1](https://github.com/Habtamu210/To-do-list/blob/main/src/modules/Task.js#L1) of Task.js file and make the appropriate changes. ♻️
